# Generated by Django 3.1.3 on 2020-11-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_app', '0026_auto_20201120_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(choices=[('Advil', 'advil'), ('Tylenol', 'tylenol'), ('Propranolol', 'propranolol'), ('Benadryl', 'benadryl')], max_length=20)),
                ('refills', models.IntegerField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.post')),
            ],
        ),
    ]
