# Generated by Django 3.1.1 on 2020-09-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20200924_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
