# Generated by Django 3.1.1 on 2020-09-24 21:51

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='obj',
            field=models.IntegerField(default=1, verbose_name=builtins.id),
            preserve_default=False,
        ),
    ]
