# Generated by Django 3.1.3 on 2020-11-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_post_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='obj',
        ),
    ]
