# Generated by Django 3.1.3 on 2020-11-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_remove_post_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='patient_name',
        ),
    ]
