# Generated by Django 3.1.3 on 2020-11-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20201113_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='doctor',
        ),
    ]
