# Generated by Django 3.1.3 on 2020-11-13 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_auto_20201113_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(choices=[('PED', 'pediatrics'), ('SRG', 'surgery'), ('TRM', 'trauma'), ('PAN', 'pandemics')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.department'),
        ),
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ForeignKey(choices=[('RED', 'red'), ('BLU', 'blue'), ('BLK', 'black'), ('GRY', 'grey'), ('WHT', 'white')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.team'),
        ),
    ]
