# Generated by Django 3.1.3 on 2020-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_auto_20201113_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default='2020-11-12'),
        ),
    ]
