# Generated by Django 3.1.3 on 2020-11-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
