# Generated by Django 3.1.3 on 2020-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_auto_20201113_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCountView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
