# Generated by Django 3.1.3 on 2020-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0020_appointmentcountview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentCountView',
        ),
    ]
