# Generated by Django 3.1.3 on 2020-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_delete_appointmentcountview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='doctor',
            field=models.CharField(choices=[('Alex Harris', 'Alex Harris'), ('Jack Doe', 'Jack Doe'), ('Xinjiang Liu', 'Xinjiang Liu'), ('Ericka Jones', 'Ericka Jones'), ('Donalad Grape', 'Donald Grape')], max_length=25),
        ),
    ]
