# Generated by Django 3.1.3 on 2020-11-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_auto_20201120_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='doctor',
            field=models.CharField(max_length=25),
        ),
    ]
