# Generated by Django 3.1.3 on 2020-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_auto_20201120_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='api_app.Tag'),
        ),
    ]
