# Generated by Django 3.1.3 on 2020-12-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0029_auto_20201209_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience',
        ),
    ]
